// Generates src/data/logos.ts: simple-icons paths (CC0) for vendors that have them,
// plus the vendor domain used for favicon fallback. Run: node scripts/gen-logos.cjs
const si = require("simple-icons");
const fs = require("fs");
const map = {
  "brain-fm": ["brain.fm"], "customer-io": ["customer.io"], factory: ["factory.ai"], fin: ["fin.ai", "siIntercom"],
  framer: ["framer.com", "siFramer"], granola: ["granola.ai"], "grok-bot": ["grok.com", "siX"], gumloop: ["gumloop.com"],
  jam: ["jam.dev"], linear: ["linear.app", "siLinear"], "magic-patterns": ["magicpatterns.com"], manus: ["manus.im"],
  mobbin: ["mobbin.com"], notion: ["notion.so", "siNotion"], posthog: ["posthog.com", "siPosthog"], railway: ["railway.com", "siRailway"],
  readwise: ["readwise.io"], resend: ["resend.com", "siResend"], supercut: ["supercut.ai"], "waking-up": ["wakingup.com"],
  warp: ["warp.dev", "siWarp"], "wispr-flow": ["wisprflow.ai"], cursor: ["cursor.com", "siCursor"], elevenlabs: ["elevenlabs.io", "siElevenlabs"],
  gamma: ["gamma.app"], "google-ai-pro": ["gemini.google.com", "siGooglegemini"], higgsfield: ["higgsfield.ai"], lovable: ["lovable.dev"],
  mercury: ["mercury.com"], n8n: ["n8n.io", "siN8n"], pangram: ["pangram.com"], replit: ["replit.com", "siReplit"], runway: ["runwayml.com"],
  "stripe-atlas": ["stripe.com", "siStripe"], supabase: ["supabase.com", "siSupabase"],
};
const out = [];
out.push("/** AUTO-GENERATED by scripts/gen-logos.cjs — vendor logo sources. simple-icons is CC0. */");
out.push("export interface LogoSource { domain: string; path?: string; hex?: string; title?: string }");
out.push("export const logoSources: Record<string, LogoSource> = {");
for (const [slug, [domain, key]] of Object.entries(map)) {
  const icon = key ? si[key] : null;
  if (key && !icon) throw new Error("missing icon " + key);
  out.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(icon ? { domain, path: icon.path, hex: icon.hex, title: icon.title } : { domain })},`);
}
out.push("};");
fs.writeFileSync("src/data/logos.ts", out.join("\n") + "\n");
console.log("wrote", Object.keys(map).length, "entries");
